xversion: '2.2'
services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    hostname: mysqldb
    volumes:
      - myqsl_data:/var/lib/mysql
    environtment:
      MYSQL_ROOT_PASSWORD:jayaswara    
    restart:
      always
    networks:
      - network_node
  app:
    build : .
    ports:
      - 8000:8000
    depends_on:
      - mysqldb
    networks:
      - network_node        
networks:
  network_node:
volumes:
  mysql_data: