name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - name: Deploy using ssh
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}
           port: 22
           script: |
            cd  forum_api
            git pull origin master
            npm install --only=prod
            docker build --tag forum_api_app .
            docker stop forum_api_app_1
            docker container rm forum_api_app_1
            docker container create --name forum_api_app_1 -p 8000:8000 forum_api_app
            docker container start forum_api_app_1
            
      #       git status
      #       npm install --only=prod
